[package]
name = "dna-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "=0.4.13"
dna = { path = "..", features = ["fuzzing"] }

[[bin]]
name = "abif_parse"
path = "fuzz_targets/abif_parse.rs"
test = false
doc = false
bench = false
