name: Generate lockfile

on:
  pull_request:
    paths:
      - Cargo.toml
      - .github/workflows/lockfile.yml

permissions:
  contents: read

jobs:
  lockfile:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Resolve added dependency
        run: cargo check
      - name: Upload resolved lockfile
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: cargo-lock
          path: Cargo.lock
          if-no-files-found: error
          retention-days: 1
